#-------------------------------
# Spring core Properties
#-------------------------------
spring:
  application:
    name: ChatGPTUsingSpringBootApplication
  main:
    banner-mode: log
  profiles:
    active: dev

#-------------------------------
# Logging Config
#-------------------------------
logging:
  level:
    com:
      online:
        shopping: DEBUG